### ISSUE TITLE
Unable to establish session

### ISSUE THREAD

**Issue by msantosh-rails** [blockchain/service-my-wallet-v3#144]
service-my-wallet-v3: 0.22.2
nodejs : 4.4.7
npm : 2.15.8

When I try to send bitcoin I am getting following Error.

1477543337188 - debug: Logging in
undefined
1477543337473 - error: Unable to establish session

Please help me to fix the error

**Comment by sergiogarcia02** [comment]
I have the same error. It gets fixed by adding the **ApiCode** (at least at the first request for a walletId).

So the solution is request an ApiCode ([here](https://blockchain.info/es/api/api_create_code)) and always include it at your requests. Ex:

    http://$IP:$PORT/merchant/$guid/balance?password=$main_password&api_code=$api_code


*- For me it also works an ApiCode requested for Payment v2 API*

**Comment by jtormey** [comment]
Hmm interesting that the api code fixes this. I'll look into it more, an api code should not be required for just fetching the balance.

**Comment by jtormey** [comment]
Just noticed #140, closing this as duplicate.
