### ISSUE TITLE
XPUB_NOT_Found

### ISSUE THREAD

**Issue by AdamLab** [blockchain/service-my-wallet-v3#180]
When i'm trying to get my xpub gap limit. I get in json 

error: XPUB_Not_Found.

I tried using CURL on Mac terminal. 

curl "https://api.blockchain.info/v2/receive/checkgap?xpub=[yourxpubhere]]&key=[yourkeyhere]"

**Comment by jtormey** [comment]
The xpub you send in that request must have a callback attached to it, since it's intended to be used along with our [Receive Payments API](https://blockchain.info/api/api_receive). To register the callback, send a request like: `https://api.blockchain.info/v2/receive?xpub=$xpub&callback=$callback_url&key=$key`. Let me know if that solves your issue.

**Comment by AdamLab** [comment]
worked fine, thanks
