### ISSUE TITLE
V2 is a very bad idea

### ISSUE THREAD

**Issue by zapacila89** [blockchain/service-my-wallet-v3#22]
Hi,

First of all congrats on a great initial API. 

I'm really interested on why on earth would you require a REST API to install a local service. The reasons are really beyond me. 

My production environment isn't built around node.js. I don't want to install node.js, I don't want to run your local service. HTTP calls wore more than enough.

Please shed some light on this ridiculously architecture change

Kind regards,
Narcis

**Comment by SlowlyDeath** [comment]
I also don't like this new API mainly because is not friendly and it requires an api key that I barely got after 1 month, 4 requests 2 requests to support desk.

**Comment by kristovatlas** [comment]
Hello,

Thanks for the feedback. The new API affords greatly improved security for users, which is why we are adamant about migrating users over. I understand that it requires more technical commitment for API users. Please feel free to reach out with any questions you have about migrating to the new API.
