### ISSUE TITLE
Response incorrect

### ISSUE THREAD

**Issue by Lanskih90** [blockchain/service-my-wallet-v3#30]
1) Make the request to receive the balance from the **wallet**, I receive **{"balance":0}** , but there is money.
2) Make the request to receive the balance from the **address**, I receive **{"balance":null,"address":"XXaddressXX","total_received":null}** , but there is money.

Why is this happening?

**Comment by Lanskih90** [comment]
Me someone answer?

**Comment by jtormey** [comment]
Hi, sorry for the delay.

This problem usually happens when the wallet data is successfully fetched from the server, but then getting the wallet history fails. This kind of behavior can happen after a login timeout (which you will see in the console as `ERR_TIMEOUT`, or in the server response as `Call to /login timed out, please try again`).

To prevent this from happening, make sure to call `/login` again after a login timeout, or when the balance is incorrect, as this will attempt to refresh the wallet history. Hopefully this information helps, I will be working on a better solution to this issue over the next few days.

This solution only works as of **v0.14.3**. To check your version number: `blockchain-wallet-service -V`

**Comment by Lanskih90** [comment]
My version 0.9.1

**Comment by jtormey** [comment]
Do you mind upgrading to a more recent version? There were several bug fixes between 0.9.1 and now. To upgrade: `npm install -g blockchain-wallet-service@1.4.3`

**Comment by Lanskih90** [comment]
Ok, thanks!

**Comment by Lanskih90** [comment]
I updated to version 0.15 to!
Now I can not login, I called, it hangs and after some time I get the error: 
> Error 504 Gateway time-out

Why is this happening?

**Comment by jtormey** [comment]
Was version 0.14.3 working for you? Does any information display in the server console when you get this error?

**Comment by Lanskih90** [comment]
> npm install -g blockchain-wallet-service@0.14.3 

This command was updated to 0.15.0  version.

>Does any information display in the server console when you get this error?

How to check this error?

**Comment by jtormey** [comment]
When you run this command: `blockchain-wallet-service start --port 3000` it will start the service. Any information output by the service will be in that window.

Does any information print out in there when you send a request and get the 504 error?

**Comment by Lanskih90** [comment]
Error: 
>Unknown API Key

But I have API Key and previously he worked!

**Comment by jtormey** [comment]
Can you go to this url to test that your api key is actually valid?
https://blockchain.info/latestblock?api_code=your_key_here

**Comment by Lanskih90** [comment]
My APi key is invalid!
I sent a request for a new key, here: https://blockchain.info/api/api_create_code
Do you can speed up the process of verification ?
Email: info@bit-changer.net
Name: BitChanger
