### ISSUE TITLE
Payment Error. Missing coins to spend 

### ISSUE THREAD

**Issue by Pufflox** [blockchain/service-my-wallet-v3#31]
Trying to do a payment I always get:

{"error":"Missing coins to spend"}

In the wallet console I get this:
No free outputs to spend
Missing coins to spend
Missing coins to spend

The wallet balance is 0.00020133
The amount I want to transfer is 0.0001

- I checked the address for unspent outputs (get 20133): https://blockchain.info/unspent?active=1HJYiBzKQGrbsDxyhae8mFYqE9Vzov6oQU
- blockchain-wallet-service -V  = 0.14.1
- wallet balance method returns 20133

Maybe there is a minimum amount to send?

**Comment by Raiymbek** [comment]
I have the same error 
https://blockchain.info/unspent?active=1JWCk25yAyNHZxrTu1gumxUNR7f7jrGV83

No free outputs to spend
Missing coins to spend
Missing coins to spend

The wallet balance is 0.0037
The amount I want to transfer is 0.0002

but i want to send from this address 1JWCk25yAyNHZxrTu1gumxUNR7f7jrGV83

I checked the address for unspent outputs i get 30000 https://blockchain.info/unspent?active=1JWCk25yAyNHZxrTu1gumxUNR7f7jrGV83
blockchain-wallet-service -V = 0.14.1

What am i doing wrong?

**Comment by jtormey** [comment]
I'm looking into what might be causing this issue now. Internally, the my-wallet service uses blockchain.info/unspent to get the unspent outputs, so it's strange that in one case it returns "No free outputs to spend", and not in the other.

How are you sending your request to the service? Does it work if you use the following curl command?

```
curl -X POST -H "Content-Type: application/json" -d '{
    "to": "toAddress",
    "from": "fromAddress",
    "amount": "10000",
    "password": "password" 
}' "http://localhost:$port/merchant/$guid/payment"
```

**Comment by Pufflox** [comment]
Using your curl command I get the same error

Now I'm using curl with php:

`$guid = "myGuid";
$main_password = "myPassword";
$second_password = "mySecondPassword";
$address = "myAddress";
$amount = 10000;

$url = "http://localhost:3000/merchant/$myGuid/payment?password=$main_password&second_password=$second_password&to=$address&amount=$amount";
$ch = curl_init();
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
$apiResponse = curl_exec($ch);	//{"error":"Missing coins to spend"}
curl_close($ch);`

**NOTES**:
- I'm not using "from" parameter
- Balance method returns the right value
- List addresses is returning an empty array (the addresses were generated using Receive Payments API V2)

I don't think this has something to do, but you never know

**Comment by jtormey** [comment]
Ah, I see the issue. The RPv2 API uses an xpub for receiving bitcoin. The address you sent to is not part of your wallet addresses, but generated from that xpub (which is why it is not found in the address list). 

The "No free outputs to spend" error happens because when the "from" field is left empty, the wallet attempts to use one of the wallet addresses to send from (and it sounds like you don't have any).

The RPv2 xpub is represented in the wallet as an "account". To send from it, set the "from" field to the account number (which for you is probably 0).

You can see all of your accounts by calling `http://localhost:3000/merchant/$guid/accounts`. Note: this account listing feature is only available as of **v0.14.2**. To upgrade: `npm install -g blockchain-wallet-service@latest`.

Let me know if this helps.

**Comment by Pufflox** [comment]
You were absolutely right, that was the problem!

I've added the account number to the "from" field and worked perfectly.

The response is a little different from the API docs (txid instead of tx_hash) but I'm sure it will be updated soon.

Thank you very much for your help!
Have a nice day!

**Comment by jtormey** [comment]
Great to hear! Thanks for pointing out that discrepancy (txid vs tx_hash), I'll add it to the docs.

**Comment by Raiymbek** [comment]
Thanks for help. I've added from = 0 and it helped to me.

**Comment by tinodj** [comment]
Why you say in your docs from is optional when it is not? 
https://blockchain.info/api/blockchain_wallet_api

**Comment by jtormey** [comment]
"from" is optional when you're not using the HD endpoints. When you're using HD accounts rather than individual addresses, you need to set the "from" parameter explicitly.

**Comment by satellite1** [comment]
@jtormey  Attempted to query /merchant/:guid/accounts/xpubs [query requests a password param and then when set issues 404. Using v19.0] so I have to ask my situation. I have two xpubs in my account. 

In relation to 'from='  
xpub1 [default] as two wallet address assigned to it.
xpub2 has none. 

So when I use from= in a string and I want to send from xpub1 address1, how would that look?

In a scenario where from=0 does it attempt to look now at xpub2 and send from that since no wallets are defined with it. 

The reason I'm asking is I have from=0 and the send is attempting to use xpub2 [even though it's not set as the default] So my assumption is default is only receive, and as you indicated 'from' has to be set explicit. 

Thanks!

**Comment by jtormey** [comment]
There's no way to send from specific addresses within an xpub. The purpose of xpubs is to make it easy to generate a new, unused address for every transaction. This is huge for security and privacy, with this method it is much more difficult for someone to look through your payment history using a block explorer.

And with xpubs, you don't have to keep track of all of these addresses, the wallet software will do it for you! So, rather than selecting specific addresses in account0 to send from, you just specify that you want to send from account0, and then the service takes care of the rest.

I hope that makes sense, the bottom line is that you don't need to worry about addresses in the account hierarchy (unless you're receiving to one of them).

I'll look into the other spending issues you're having, the service should not be defaulting to xpub1 if you set from=0.

**Comment by satellite1** [comment]
I have since solved this issue with designating account Xpub {0,1 etc.}. What was causing the issue was my assumption of the dashboard - default option. Setting an xpub to default, you would believe that would be xpub = 0, but it does not. And yes what you state, makes perfect sense. 

Thanks!

**Comment by jtormey** [comment]
Great to hear, I'll add some of the points discussed in this issue to the docs for clarity.

**Comment by claudecigoularte** [comment]
I'm with its problem. I'm using from, and not working.
