### ISSUE TITLE
Payment method unexpected error

### ISSUE THREAD

**Issue by wishexxt** [blockchain/service-my-wallet-v3#314]
blockchain-wallet-service v0.26.0
Node v8.9.3
NPM v5.5.1

Hello, i try to send some btc from my main blockchain wallet
i included this params to query:
- guid
- from_index = 0, cause it's my main wallet
- to_btc_address
- pass
- amount in satoshi to send

I can call balance without any errors.
and there is an error-log for payment:

blockchain-wallet-service start --log-level debug --port 3000
1514696326121 - debug: Debug messages are enabled
1514696326123 - info: blockchain.info wallet service v0.26.0 running on http://127.0.0.1:3000
1514696326978 - debug: Logging in
1514696327185 - debug: Created new session token
1514696327364 - debug: Fetched wallet
1514696327560 - debug: Decrypted wallet
1514696327913 - debug: Fetching wallet history
1514696329030 - error: [object Object]

in console i only have - Unexpected error, please try again

**Comment by wishexxt** [comment]
@jtormey can you please help me with this problem?

**Comment by bobozar** [comment]
Same error here. It's sad that the package developer(s) is not active. Blockchain support is nothing to write home about. We need a good wallet provider!

**Comment by ej23lee** [comment]
I recently started using the service and have encountered the same issue. I decided to clone the project and run a local instance instead of using their service to debug.

In their client code, they tend to assert their errors which will print out the error line you get. However sometimes they try to log objects. To debug I had to edit their asserts. For making payments, I edited their `function Transaction(payment, emitter)` in `blockchain-wallet-client/lib/transaction.js`. Anytime you see them asserting something and returning an object, just wrap it with `JSON.stringify`. Hopefully this helps.
