### ISSUE TITLE
Does the password need to be sent in the url query in plain text?

### ISSUE THREAD

**Issue by dwanderton** [blockchain/service-my-wallet-v3#32]
Is there a more secure way than this to utilize the password. Password could be intercepted by anyone monitoring network requests etc so on and so forth...

**Comment by kristovatlas** [comment]
In what environment will you be running this?

Most people using this module will be running it on localhost, in which case the network traffic will remain on the same host and not traverse any actual networks.

As for including the password in a URL, you can submit the parameters via POST method instead of GET. This will prevent the password from being cached by any applications that tend to log URLs but not the body of HTTP requests.
