### ISSUE TITLE
Callback not working

### ISSUE THREAD

**Issue by proBeejay141** [blockchain/service-my-wallet-v3#330]
I have api key, but the callback url is not call whenever btc is send to the generated address, please help

**Comment by ChemicalSerenity** [comment]
Can confirm. Callbacks have stopped since January 27th. We've worked around it by grabbing updates directly from the stream to determine if payments have been made, but without the callbacks we can't let blockstream know that the address is no longer in use and so we get up to the 20 address limit pretty quick so we've bumped the upper limit on issued addresses.

Blockstream -- we really need an answer. Your trouble ticket system has a header that says you're overloaded... does that mean it takes a week to address a tech problem that would leave many people completely dead in the water?

**Comment by proBeejay141** [comment]
Please, can you elaborate on the workaround. Thanks

**Comment by proBeejay141** [comment]
help can you explain the work around...please

**Comment by n1v2s3r4** [comment]
how to blocks genarated

**Comment by kiahmed** [comment]
how do you even pass callback url ? The doc doesnt say anything about it. is it working now btw?

**Comment by stan-asiegbu** [comment]
Please what is the work around?

**Comment by jtormey** [comment]
This issue is not related to this repository. Although I believe it has been fixed. For future issues with the Receive Payments API, please open a support ticket at support.blockchain.com.
