### ISSUE TITLE
Please tag release versions and create a develop branch

### ISSUE THREAD

**Issue by nebaughman** [blockchain/service-my-wallet-v3#67]
*Service v0.17.2, Node v0.12.10*

Some suggestions for making it easier to follow development of this project:

* Tag release versions in the `master` branch. I am running Wallet API v0.17.2 (installed via npm). The code here is newer, but I'm not sure what has changed since this release, nor what is in the next release versus ongoing development. Tags make it easier to refer to documentation/issues/code of the version I have and see what has changed.
* Develop in a `develop` branch. Merge to `master` (and tag) when a stable version is ready. This clarifies what is a work-in-progress versus stable code. This also allows patches/hotfixes to be made to the last tagged version even if the work-in-progress (`develop`) code is not yet ready for release.

**Comment by nebaughman** [comment]
I see Milestones being used now - excellent!

**Comment by jtormey** [comment]
Yes, we have Milestones now!

I've changed up the dev workflow in a few ways (based on your comments above):
* Branches are being merged into the dev branch now instead of directly to master
* When a milestone is completed, dev will be merged into master, tagged, and released with a new minor version
* Hot fixes will be applied directly to master and will increase the patch version number

If you have other suggestions feel free to post them here.
