### ISSUE TITLE
public note

### ISSUE THREAD

**Issue by html5-ninja** [blockchain/service-my-wallet-v3#87]
in github doc : note - public note to include with the transaction (optional, limit 255 characters, will fail if any transaction outputs are greater than 500000 satoshi)
on api doc : 
$note A public note to include with the transaction -- can only be attached when outputs are greater than 0.005 BTC. (Optional)

So my question to attach a public note transaction should  be greater then 500000 satoshi or not ? thx

**Comment by jtormey** [comment]
Sorry, seems like there was a typo in the README docs, I'll fix that now. All transaction outputs (including change outputs) need to be greater than 500000 satoshi. Thanks for pointing that out!

**Comment by robsonhortela** [comment]
I'm trying to make a transfer in amount of 5000000 satoshi, and its returning "There is an output too small to publish a note"

**Comment by html5-ninja** [comment]
Same,

**Comment by jtormey** [comment]
The problem here is most likely with the change output.

**Example case**
Let's say your transaction of 5000000 is consuming 3 outputs that all have the same value: 1670000. These outputs don't add up to the amount you want to spend exactly, together they equal 5010000. What this means is that the change output (the amount going back to you) is 10000 satoshi. 10000 is less than 500000, so you see the error.

**Why do we do this?**
Mainly to prevent the public note feature from being spammed. The reason the change output is taken into account is because we can't actually tell which output is the change output in many cases. The change address may be another bitcoin address owned by the sender, or an address within the sender's HD account, so to us it just looks like a every other output in the transaction.

**So what's the solution?**
For now, I would recommend using the public note option sparingly. In the longer term, this is something that needs to be taken care of on my end. I'll look into changing the restriction in order to improve the usability of this feature.

Until then, reopening this issue.

**Comment by html5-ninja** [comment]
thx for the reply
so technically it's not working at all, even using the web wallet I can't send a public note , maybe you should simply remove this feature from the api for the moment cause it induce error on sending transaction.

**Comment by jtormey** [comment]
Public note is no longer an option
